/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedPdfRouteImport } from './routes/_authenticated/pdf'
import { Route as AuthenticatedPapersRouteImport } from './routes/_authenticated/papers'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedFlashcardsRouteImport } from './routes/_authenticated/flashcards'
import { Route as AuthenticatedExamRouteImport } from './routes/_authenticated/exam'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedBookmarksRouteImport } from './routes/_authenticated/bookmarks'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPdfRoute = AuthenticatedPdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPapersRoute = AuthenticatedPapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFlashcardsRoute = AuthenticatedFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamRoute = AuthenticatedExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookmarksRoute = AuthenticatedBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exam': typeof AuthenticatedExamRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/papers': typeof AuthenticatedPapersRoute
  '/pdf': typeof AuthenticatedPdfRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exam': typeof AuthenticatedExamRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/papers': typeof AuthenticatedPapersRoute
  '/pdf': typeof AuthenticatedPdfRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/bookmarks': typeof AuthenticatedBookmarksRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exam': typeof AuthenticatedExamRoute
  '/_authenticated/flashcards': typeof AuthenticatedFlashcardsRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/papers': typeof AuthenticatedPapersRoute
  '/_authenticated/pdf': typeof AuthenticatedPdfRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/assignments'
    | '/bookmarks'
    | '/chat'
    | '/dashboard'
    | '/exam'
    | '/flashcards'
    | '/notes'
    | '/papers'
    | '/pdf'
    | '/planner'
    | '/profile'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/assignments'
    | '/bookmarks'
    | '/chat'
    | '/dashboard'
    | '/exam'
    | '/flashcards'
    | '/notes'
    | '/papers'
    | '/pdf'
    | '/planner'
    | '/profile'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/assignments'
    | '/_authenticated/bookmarks'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/exam'
    | '/_authenticated/flashcards'
    | '/_authenticated/notes'
    | '/_authenticated/papers'
    | '/_authenticated/pdf'
    | '/_authenticated/planner'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pdf': {
      id: '/_authenticated/pdf'
      path: '/pdf'
      fullPath: '/pdf'
      preLoaderRoute: typeof AuthenticatedPdfRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/papers': {
      id: '/_authenticated/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof AuthenticatedPapersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flashcards': {
      id: '/_authenticated/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AuthenticatedFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exam': {
      id: '/_authenticated/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof AuthenticatedExamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookmarks': {
      id: '/_authenticated/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AuthenticatedBookmarksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedBookmarksRoute: typeof AuthenticatedBookmarksRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamRoute: typeof AuthenticatedExamRoute
  AuthenticatedFlashcardsRoute: typeof AuthenticatedFlashcardsRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedPapersRoute: typeof AuthenticatedPapersRoute
  AuthenticatedPdfRoute: typeof AuthenticatedPdfRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedBookmarksRoute: AuthenticatedBookmarksRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamRoute: AuthenticatedExamRoute,
  AuthenticatedFlashcardsRoute: AuthenticatedFlashcardsRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedPapersRoute: AuthenticatedPapersRoute,
  AuthenticatedPdfRoute: AuthenticatedPdfRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
